server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://ep-damp-wildflower-a1p5bcsx-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_sby5oYMcw3OV
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: ignored
      password: ignored

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

groq:
  api:
    key: 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
    url: https://api.groq.com/openai/v1/chat/completions
    model: llama-3.3-70b-versatile
    max-tokens: 1500

verdex:
  cors:
    allowed-origins: https://verdexai.pages.dev

encryption:
  key: VerdexSecretKey2024ChangeThisNow!

file:
  upload-dir: uploads

application:
  base-url: https://verdexai.onrender.com

